development:
  dialect: "mysql"
  database: "buffalo_learning_development"
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: "mysql"

test:
  dialect: "mysql"
  database: "buffalo_learning_test"
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: "mysql"

production:
  dialect: "mysql"
  database: "buffalo_learning_production"
  host: "localhost"
  port: "3306"
  user: "root"
  password: "mysql"
